[build]
  command = "npm run test && npm run build"
  publish = ".next"

[functions]
  included_files = ["data/vaccineData/*.json"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_GA_ID = "G-3N8VWQ2KCM"
  NEXT_PUBLIC_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_GA_ID = "G-LGFTVFGLKX"
  NEXT_PUBLIC_ENVIRONMENT = "deploy-preview"
