name: Run Fetchy Fetch Boi
on:
  pull_request:
  repository_dispatch:
  workflow_dispatch:
    branches:
      - main

jobs:
  fetchy:
    name: Run Fetchy
    runs-on: ubuntu-latest
    env:
      # set this secret, you can get the value from this discord message https://discord.com/channels/658523382442360866/903771050385502239/904216952141152328
      DISCORD_WEBHOOK: $ {{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5
      - name: Load global environment variables
        run: cat .github/config/global.env >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Fetchy
        run: npm run fetch-boi
      - name: Cache fetchy output
        id: cache-data
        uses: actions/cache@v2
        with:
          path: ./data
          key: data-${{ github.run_id }}-${{ github.run_number }}
  committy:
    name: Commit Fetchy Results
    runs-on: ubuntu-latest
    needs: fetchy
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5
        with:
          token: ${{ secrets.PAT }}
      - name: Cache fetchy output
        id: cache-data
        uses: actions/cache@v2
        with:
          path: ./data
          key: data-${{ github.run_id }}-${{ github.run_number }}
      - name: Fail if cache hit is unsuccessful
        if: steps.cache-data.outputs.cache-hit != 'true'
        run: exit 1
      - name: Commit data
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Adding/Updating the latest MoH Data"
