name: Tests
on:
  pull_request:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Load global environment variables
        run: cat .github/config/global.env >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
