name: Verify Run Fetchy
on:
  pull_request:

jobs:
  fetchy:
    name: Verify Run Fetchy
    runs-on: ubuntu-latest
    env:
      # set this secret, you can get the value from this discord message https://discord.com/channels/658523382442360866/903771050385502239/904216952141152328
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      SEND_DISCORD_NOTIFICATIONS: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Load global environment variables
        run: cat .github/config/global.env >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Run Fetchy
        run: npm run fetchy
      - name: Note any files generated
        run: git status
